// 125 products from the Divine Traders catalog. Prices default to null so
// wholesale buyers see "₹—" until the admin fills them in via Edit Mode.
export const SEED_PRODUCTS = [
  // FRAGRANCES & AIR CARE
  { brand: 'Killer', name: 'Storm / Cyclone / Wave', category: 'Fragrances', description: 'Gas-Free Deodorant Spray', packaging: 'Aerosol spray canister', sort_order: 1 },
  { brand: 'Beardo', name: 'Don / Mafia', category: 'Fragrances', description: 'Eau De Parfum Spray', packaging: 'Dark glass bottle & unit box', sort_order: 2 },
  { brand: 'Envy', name: 'Exclusive Collection (Fiery / Dark)', category: 'Fragrances', description: 'Eau De Parfum (100ml / 50ml)', packaging: 'Display carton + inner EDP bottle', sort_order: 3 },
  { brand: 'Kelyn', name: 'Invisible Men', category: 'Fragrances', description: 'Eau De Toilette (100ml)', packaging: 'Glass bottle + outer carton', sort_order: 4 },
  { brand: 'Insight', name: 'Perfume Deodorant Spray', category: 'Fragrances', description: 'Long-Lasting Body Spray', packaging: 'Matte aerosol bottle', sort_order: 5 },
  { brand: 'Clensta', name: 'Madrid / Milan / Barcelona', category: 'Fragrances', description: 'Body Perfume Spray Trio', packaging: 'Color-coded canister set', sort_order: 6 },
  { brand: 'Signature', name: 'Gardenia / Misty Jasmine / Tuberose', category: 'Fragrances', description: 'Home & Car Air Freshener', packaging: 'Spray bottle with floral graphics', sort_order: 7 },
  { brand: 'Lure', name: 'Aqua Fresh / Green Valley / Lemon / Oud & Saffron / Rose', category: 'Fragrances', description: 'Air Freshener Spray (220ml)', packaging: 'Aerosol scent canisters', sort_order: 8 },

  // BASE, PRIMERS & FIXERS
  { brand: 'Daily Life Forever52', name: 'Ultra Definition Liquid Foundation', category: 'Base & Complexion', description: 'Full Coverage Foundation', packaging: 'Glass pump bottle + box', sort_order: 9 },
  { brand: 'Daily Life Forever52', name: 'Dewy Glow Prime & Fine Fixing Spray', category: 'Base & Complexion', description: 'Makeup Setting Mist', packaging: 'Spray mister bottle', sort_order: 10 },
  { brand: 'Half-Half', name: 'Glam Hold 2-in-1 Shimmer Spray', category: 'Base & Complexion', description: 'Highlighter & Fixer (Holo Pink / Gold / Rose Gold)', packaging: 'Shimmer mist bottle', sort_order: 11 },
  { brand: 'Half-Half', name: 'Bake Out Loose Powder', category: 'Base & Complexion', description: 'Finishing Setting Powder', packaging: 'Compact tub + sifter', sort_order: 12 },
  { brand: 'Hilary Rhoda', name: 'Staying Up / Shimmer Stay', category: 'Base & Complexion', description: 'Ultimate Makeup Fixer Spray', packaging: 'Glossy spray bottle', sort_order: 13 },
  { brand: 'Color Strokes', name: 'Fit Skin BB Cream (CS-85 / CS-86 / CS-87 / CS-91)', category: 'Base & Complexion', description: 'Cover Foundation & Primer (40ml)', packaging: 'Squeeze tube + carton', sort_order: 14 },
  { brand: 'Nexa', name: 'Super HD Flawless Finish', category: 'Base & Complexion', description: 'CC / BB Cushion Foundation', packaging: 'Cushion box + inner compact', sort_order: 15 },
  { brand: 'Maliao', name: 'You Entice Penstick', category: 'Base & Complexion', description: 'Foundation Stick (10g)', packaging: 'Twist-up penstick tube', sort_order: 16 },
  { brand: 'Kiss Love', name: 'Strobe Cream 3-in-1', category: 'Base & Complexion', description: 'Primer, Highlighter & Moisturizer (Pink / Gold)', packaging: 'Squeezable tube', sort_order: 17 },

  // EYES, BROWS & PALETTES
  { brand: 'Charmicok', name: 'Butterfly Series (726A-6 / 729E / 729B)', category: 'Eyes & Palettes', description: 'Blusher / Eyeshadow / Highlighter / Lip Cream / Eyebrow Powder', packaging: 'Display unit box + open palette', sort_order: 18 },
  { brand: 'Angel Rose', name: 'Soft Glam Palette', category: 'Eyes & Palettes', description: '18-Color Eyeshadow Palette', packaging: 'Open pan palette + box', sort_order: 19 },
  { brand: 'Angel Rose', name: 'Diamond Highlighter', category: 'Eyes & Palettes', description: 'Iridescent Powder Compact', packaging: 'Single pan compact + box', sort_order: 20 },
  { brand: 'Lakmé', name: 'Sun Expert / Absolute Radiance', category: 'Eyes & Palettes', description: 'Compact Powder (SPF 40 / SPF 23)', packaging: 'Mirrored compact', sort_order: 21 },
  { brand: 'Rose', name: 'Professional Makeup Artist Palette', category: 'Eyes & Palettes', description: '24x Eyeshadow, 2x Blush, 4x Lipstick, 4x Highlighter, 3x Brow', packaging: 'Fold-out kit case', sort_order: 22 },
  { brand: 'Any Lady', name: 'Lush Petals / Heartthrob Collection', category: 'Eyes & Palettes', description: 'Multi-Color All-In-One Makeup Palette', packaging: 'Floral printed case', sort_order: 23 },
  { brand: 'Mecow', name: 'Chess Highlight Series', category: 'Eyes & Palettes', description: 'Fine Powder Highlighter', packaging: 'Illustration display box', sort_order: 24 },
  { brand: '3Q Beauty', name: 'Smart Glow (HLT-099)', category: 'Eyes & Palettes', description: 'Liquid Face Highlight', packaging: 'Dropper glass bottle', sort_order: 25 },
  { brand: 'Kiyooos', name: '24-Hour Tattoo Eyeliner', category: 'Eyes & Palettes', description: 'Waterproof Liquid Eyeliner', packaging: 'Mirror handle tube + box', sort_order: 26 },
  { brand: 'ADS', name: 'Cosmetics Pencil Original Artist', category: 'Eyes & Palettes', description: 'Dual Function Creamy Eyeliner & Eye Color', packaging: '144-piece box display', sort_order: 27 },
  { brand: 'ADS', name: 'Perfect Eyeliner & Lipliner', category: 'Eyes & Palettes', description: '2-in-1 Waterproof Cosmetic Pencil', packaging: 'Display card pack', sort_order: 28 },
  { brand: 'Golden Rose', name: '5D Eyeliner', category: 'Eyes & Palettes', description: 'Water Proof Liquid Eyeliner', packaging: 'Precision applicator tube', sort_order: 29 },
  { brand: 'Swiss Beauty', name: 'Bold Matt Lipliner (Sandy Pond)', category: 'Eyes & Palettes', description: 'Waterproof Lip & Eye Liner', packaging: 'Wood pencil', sort_order: 30 },
  { brand: 'MSYAHO', name: 'Professional Makeup Palette (YH3165)', category: 'Eyes & Palettes', description: 'Eyeshadow Palette Set', packaging: 'Display tray + case', sort_order: 31 },
  { brand: 'Hold Morning', name: 'Sky High Mascara & Eyeliner (W181)', category: 'Eyes & Palettes', description: 'Long-Wear Volumizing Mascara', packaging: 'Display tray pack', sort_order: 32 },

  // LIP CARE, COLORS & GLOSSES
  { brand: 'Crazy Girl', name: 'Fancy Creamy Lipstick (CG-867)', category: 'Lip Products', description: 'Matte Lipstick Set', packaging: 'Bullet casing + display box', sort_order: 33 },
  { brand: 'Crazy Girl', name: 'Shine For You Lip Oil (CG-677 / CG-702)', category: 'Lip Products', description: 'Hydrating Lip Oil Tints', packaging: 'Bunny display tray + tubes', sort_order: 34 },
  { brand: 'Crazy Girl', name: 'Aloe Extract Lipstick', category: 'Lip Products', description: 'Nourishing Aloe Lip Balm / Stick', packaging: 'Green bullet tube', sort_order: 35 },
  { brand: 'Color 21', name: 'Soulmate / Too Hot To Handle', category: 'Lip Products', description: 'Matte Liquid Lipcolor', packaging: 'Multi-shade box pack', sort_order: 36 },
  { brand: 'Color 21', name: 'Magic Blossom Liquid Lip Color', category: 'Lip Products', description: '12-Shade High Pigment Lip Color', packaging: 'Set box + liquid tubes', sort_order: 37 },
  { brand: 'Kiss Bliss', name: 'Velvet Matte Lip Color', category: 'Lip Products', description: 'Matte Lip Stick', packaging: 'Slim twist-up stick', sort_order: 38 },
  { brand: 'Hold Morning', name: 'Strawberry / Choco Fruit Gloss & Blush (HF0106 / HL64143 / HL6413)', category: 'Lip Products', description: 'Liquid Blush & Fruit Gloss', packaging: 'Fruit theme counter display', sort_order: 39 },
  { brand: 'Gentle Beauty', name: 'Sweet Cake / Cute Love Gloss (GB-2641)', category: 'Lip Products', description: '24H Waterproof Lip Gloss', packaging: 'Dessert box + mini pots', sort_order: 40 },
  { brand: 'Moccallure', name: 'Hello Kitty Liquid Blush Display', category: 'Lip Products', description: 'Sweet Pink Blush Set', packaging: 'Pop-up counter display', sort_order: 41 },
  { brand: 'Moccallure', name: '3-in-1 Cute Lip Set (Moc1332)', category: 'Lip Products', description: 'Bear-Themed Gloss & Tint Pots', packaging: 'Tray pack + individual pots', sort_order: 42 },
  { brand: 'Ocean Beauty', name: 'Looking Charm Magic Liquid Blush (OBEL-411)', category: 'Lip Products', description: 'Color Changing Liquid Blush', packaging: 'Squeeze tube + window box', sort_order: 43 },
  { brand: 'Meike Glamour', name: 'Lipgloss & Lip Liner Set (MK314 / MK44)', category: 'Lip Products', description: 'Lipgloss + Matching Liner Duo', packaging: '24-piece box display', sort_order: 44 },
  { brand: 'Rom-Com', name: 'Matte Love Liquid Lip Color', category: 'Lip Products', description: 'By Face Tech Liquid Lipcolor', packaging: 'Display card pack', sort_order: 45 },
  { brand: 'Milky Glow', name: 'Candy Floss Matte Lipstick (Item No. 90)', category: 'Lip Products', description: '12 Amazing Shades Creamy Matte', packaging: 'Multi-pack display tray', sort_order: 46 },
  { brand: 'Huda Matte Me', name: 'Lip Tint & Lipgloss (X-679 / X-600)', category: 'Lip Products', description: 'Fashion Color Long Lasting Tint', packaging: 'Display box + wands', sort_order: 47 },
  { brand: 'Ebony London', name: 'Sangna Liquid Sindoor (Red / Suhaag)', category: 'Lip Products', description: 'Traditional Red Liquid Sindoor', packaging: 'Applicator bottle + box', sort_order: 48 },
  { brand: "I'm Bridal Sleek", name: 'Bridal Lip Tint Set', category: 'Lip Products', description: 'Glitter Red Liquid Lip Tint', packaging: '6-piece clear pouch pack', sort_order: 49 },

  // SKINCARE, CLEANSERS & SUNSCREEN
  { brand: 'Der Duft', name: 'Stay Glowing Foaming Face Wash', category: 'Skincare', description: 'Hyaluronic Acid & Blueberry Extract', packaging: 'Foam pump bottle + box', sort_order: 50 },
  { brand: 'Der Duft', name: 'Acne Solution Serum Foam Cleanser', category: 'Skincare', description: 'Salicylic Acid Cleanser (100ml)', packaging: 'Squeeze tube', sort_order: 51 },
  { brand: 'Der Duft', name: 'Urban White Foaming Cleanser', category: 'Skincare', description: 'Germany Formulation SLS-Free', packaging: 'Unit box dispenser', sort_order: 52 },
  { brand: 'Der Duft', name: 'Instant Glow Scrub', category: 'Skincare', description: 'Hyaluronic Acid & Pearl Powder (300g)', packaging: 'Wide-mouth tub jar', sort_order: 53 },
  { brand: 'Der Duft', name: 'Glow Up Sunscreen SPF 50 PA+++', category: 'Skincare', description: 'Niacinamide & Vitamin C Avocado Extract', packaging: 'Sun protection tube', sort_order: 54 },
  { brand: 'Der Duft', name: 'Aqua Shield UV Sunscreen SPF 50 PA+++', category: 'Skincare', description: 'Kojic Acid & Vitamin E Kesar Extract', packaging: 'Sun protection tube', sort_order: 55 },
  { brand: 'Wanwan', name: 'Barrier Repair Hydration Gentle Face Wash', category: 'Skincare', description: '5 Ceramides & Rice Water', packaging: 'Squeeze tube (100ml)', sort_order: 56 },
  { brand: 'Wanwan', name: 'Deep Pore Clean Facial Foam Cleanser', category: 'Skincare', description: 'Seaweed & Lotus Flower', packaging: 'Squeeze tube (100ml)', sort_order: 57 },
  { brand: 'Wanwan', name: 'Let It Glow Super Glow Face Wash', category: 'Skincare', description: 'Vitamin C + Papaya Enzyme', packaging: 'Squeeze tube (100ml)', sort_order: 58 },
  { brand: 'Wanwan', name: 'Vitamin-C Gel', category: 'Skincare', description: 'Kojic Acid & Sea Buckthorn (200g)', packaging: 'Gel jar', sort_order: 59 },
  { brand: 'Wanwan', name: 'De-Tan Cream Insta Whitening', category: 'Skincare', description: 'Clove Oil & Rice Milk Tan Remover', packaging: 'Skincare tub', sort_order: 60 },
  { brand: 'Winyfred', name: 'Korean Glow Facial Serum', category: 'Skincare', description: 'Propolis & Niacinamide (30ml)', packaging: 'Glass serum bottle with dropper', sort_order: 61 },
  { brand: 'Winyfred', name: 'Pinkish Radiance Face Serum', category: 'Skincare', description: 'Korean Fermentation Luxury Radiance', packaging: 'Glass serum bottle with dropper', sort_order: 62 },
  { brand: 'Winyfred', name: 'Organic Rose Water Mist', category: 'Skincare', description: '100% Pure Rose Extract Hydrating Mist', packaging: 'Clear spray bottle', sort_order: 63 },
  { brand: 'Winyfred', name: 'Korean Glass Skin Glow Scrub', category: 'Skincare', description: 'Niacinamide & Alpha Arbutin (200g)', packaging: 'Scrub tub', sort_order: 64 },
  { brand: 'Pattaya', name: 'Oil-Control Acne Cleanser', category: 'Skincare', description: '2% Salicylic Acid Cleanser', packaging: 'Pump dispenser bottle', sort_order: 65 },
  { brand: 'Pattaya', name: 'Ultra Gentle Foaming Cleanser', category: 'Skincare', description: 'Vitamin C & Kojic Acid', packaging: 'Pump dispenser bottle', sort_order: 66 },
  { brand: 'Pattaya Queen', name: 'Blush Beauty Nourish Cream', category: 'Skincare', description: 'Moisturizing Cream (SPF 25)', packaging: 'Facial cream tube', sort_order: 67 },
  { brand: 'Lotus Herbals', name: 'Radiance Boost Ubtan Face Wash', category: 'Skincare', description: 'Turmeric, Sandalwood & Rose Water', packaging: 'Squeeze tube', sort_order: 68 },
  { brand: 'Suria Femme', name: 'Ultra Matte Water Gel Sunscreen Spray', category: 'Skincare', description: 'SPF 50 PA++++ France Formulation', packaging: 'Aerosol spray canister', sort_order: 69 },
  { brand: 'Suria Femme', name: 'Cool Burst Sunscreen Spray', category: 'Skincare', description: 'SPF 50 PA++++ Blue Light Filter', packaging: 'Aerosol spray canister', sort_order: 70 },
  { brand: 'Dr. Rashel', name: 'Beauty Elixirs Rice Water Series', category: 'Skincare', description: 'Scrub, Gel, Cream & Face Pack', packaging: 'Glass skincare jars', sort_order: 71 },
  { brand: 'Dr. Rashel', name: 'Beauty Elixirs Aloe Vera Series', category: 'Skincare', description: 'Pure, Fresh, Whitening Soothing Gel', packaging: 'Skincare jar set', sort_order: 72 },
  { brand: 'Dr. Rashel', name: 'Bamboo Charcoal Mask Cream', category: 'Skincare', description: 'Oil Control Anti-Blackhead Mask', packaging: 'Facial cream tube', sort_order: 73 },
  { brand: 'Dr. Rashel', name: 'AM2PM De-Tan Sunscreen', category: 'Skincare', description: 'SPF 50 PA+++ De-Tan Protection', packaging: 'Sunscreen tube', sort_order: 74 },
  { brand: 'Glow & Lovely', name: 'Bright Multi Vitamin Serum in Cream', category: 'Skincare', description: 'Re-New Bright Facial Cream', packaging: 'Unit box + cream tube', sort_order: 75 },
  { brand: 'Sadoer', name: 'Bubble Milk Tea Hand Cream Set', category: 'Skincare', description: 'Strawberry / Green Tea / Orange / Coffee / Blueberry', packaging: '5-piece moisturizer tube set', sort_order: 76 },

  // FACIAL KITS
  { brand: 'Shills Professional', name: 'Retinol Facial Kit', category: 'Facial Kits', description: 'Glow Boosting & Flaky Skin Removal', packaging: 'Multi-step treatment box', sort_order: 77 },
  { brand: 'Shills Professional', name: 'Hydra Facial Kit', category: 'Facial Kits', description: 'Refining & Smoothening Soft Skin', packaging: 'Multi-step treatment box', sort_order: 78 },
  { brand: 'Shills Professional', name: 'H2O Anti-Aging Facial Kit', category: 'Facial Kits', description: 'Glow Boosting & Skin Toning', packaging: 'Multi-step treatment box', sort_order: 79 },
  { brand: 'Shills Professional', name: 'Korean Glass Glow Facial Kit', category: 'Facial Kits', description: 'Removes Surface Dirt & Brightens', packaging: 'Multi-step treatment box', sort_order: 80 },
  { brand: 'Shills Professional', name: 'Rice Skin Brightening Facial Kit', category: 'Facial Kits', description: 'Hydrates & Cleanses Skin', packaging: 'Multi-step treatment box', sort_order: 81 },
  { brand: 'Shills Professional', name: 'Salicylic Acid Facial Kit', category: 'Facial Kits', description: 'Removes Dead Skin & Brightens', packaging: 'Multi-step treatment box', sort_order: 82 },
  { brand: 'Shills Professional', name: 'Mix Fruit Facial Kit', category: 'Facial Kits', description: 'Nourishing & Spotless Radiant Skin', packaging: 'Multi-step treatment box', sort_order: 83 },
  { brand: 'Shills Professional', name: 'Hyaluron Acid Anti-Aging Kit', category: 'Facial Kits', description: 'Hydrating & Softening Treatment', packaging: 'Multi-step treatment box', sort_order: 84 },
  { brand: 'Shills Professional', name: 'Vitamin C Facial Kit', category: 'Facial Kits', description: 'Cleansing & Skin Brightening', packaging: 'Multi-step treatment box', sort_order: 85 },
  { brand: 'Shills Professional', name: 'Gold Facial Kit', category: 'Facial Kits', description: 'Skin Toning & Moisturising Natural Glow', packaging: 'Multi-step treatment box', sort_order: 86 },
  { brand: 'Shills Professional', name: 'Diamond Sparkle Facial Kit', category: 'Facial Kits', description: 'Revive, Smoothen & Anti-Aging', packaging: 'Multi-step treatment box', sort_order: 87 },
  { brand: 'Shills Professional', name: 'Special Occasion Bridal Glow 7-in-1 Kit', category: 'Facial Kits', description: 'Removes Suntan & Dark Spots', packaging: '7-in-1 treatment box', sort_order: 88 },
  { brand: 'Shills Professional', name: 'Diamond Glow Luminous Shine 7-in-1 Kit', category: 'Facial Kits', description: 'Restores Youthful Skin & Texture', packaging: '7-in-1 treatment box', sort_order: 89 },
  { brand: 'Shills Professional', name: 'Body Polishing Kit', category: 'Facial Kits', description: 'High Strength Hydrating & Moisturizing', packaging: 'Salon treatment box', sort_order: 90 },
  { brand: 'Shills Professional', name: 'Pedicure Hand & Foot Care 6-in-1 Kit', category: 'Facial Kits', description: 'Soothes & Relaxes Skin', packaging: '6-in-1 pedicure kit box', sort_order: 91 },
  { brand: 'Astaberry', name: 'Papaya Facial Kit', category: 'Facial Kits', description: 'Helps Reduce Pigmentation & Blemishes (6 Steps)', packaging: 'Step-by-step box set', sort_order: 92 },
  { brand: 'Astaberry', name: 'Wine Facial Kit', category: 'Facial Kits', description: 'Advanced Anti-Aging Facial (6 Steps)', packaging: 'Step-by-step box set', sort_order: 93 },
  { brand: 'Astaberry', name: 'Bridal Facial Kit', category: 'Facial Kits', description: 'Enhanced Glow & Dazzling Radiance (6 Steps)', packaging: 'Step-by-step box set', sort_order: 94 },
  { brand: 'Astaberry', name: 'Skin Brightening Kit', category: 'Facial Kits', description: 'Advanced Formula with Free Gold Bleach', packaging: 'Box set with free bleach', sort_order: 95 },
  { brand: 'Astaberry', name: 'Gold Facial Kit', category: 'Facial Kits', description: 'Glow & Shine for All Skin Types (5 Steps)', packaging: 'Step-by-step box set', sort_order: 96 },
  { brand: 'Astaberry', name: 'Diamond Facial Kit', category: 'Facial Kits', description: 'The Ultimate Glow & Radiance (5 Steps)', packaging: 'Box set with free bleach', sort_order: 97 },
  { brand: 'Shahnaz Husain', name: '5G Effect Skin Whitening Kit', category: 'Facial Kits', description: 'Timeless Youth Skin Polishing & Purification', packaging: 'Professional power salon box', sort_order: 98 },
  { brand: 'Shahnaz Husain', name: 'Cellular Glow 24K Gold Kit', category: 'Facial Kits', description: '24K Gold Leaves, Papaya & Horse Chestnut', packaging: 'Professional power salon box', sort_order: 99 },
  { brand: 'Lotus Herbals', name: 'Radiant Gold Facial Kit', category: 'Facial Kits', description: 'Revitalizing Effect for Great Skin Glow', packaging: '4-step salon grade box', sort_order: 100 },
  { brand: 'Lotus Herbals', name: 'Red Wine Facial Kit', category: 'Facial Kits', description: 'Tightening & Skin Repair 5-in-1 Pack', packaging: 'Paraben-free salon box', sort_order: 101 },

  // HAIR CARE, REMOVAL & ACCESSORIES
  { brand: 'Enzo', name: 'Keratin Nutrition Hair Treatment', category: 'Hair Care', description: 'Nourishing Hair Mask (1000ml)', packaging: 'Large professional treatment tub', sort_order: 102 },
  { brand: 'Enzo', name: 'Premium Hair Spray', category: 'Hair Care', description: 'Stronghold Residue-Free Spray (420ml)', packaging: 'Styling spray canister', sort_order: 103 },
  { brand: 'Winyfred', name: 'Anti Hair Fall Volume Boost Shampoo', category: 'Hair Care', description: 'Omega-6, Hyaluronic Acid & Rice Protein (250ml)', packaging: 'Shampoo bottle', sort_order: 104 },
  { brand: 'Winyfred', name: 'Keratin and Silky Hair Shampoo', category: 'Hair Care', description: 'Aloe Vera, Ginseng & Argan Oil (250ml)', packaging: 'Shampoo bottle', sort_order: 105 },
  { brand: 'Winyfred', name: 'Longer Stronger Hair Shampoo', category: 'Hair Care', description: 'Niacinamide, Pro-Vitamin B5 & Amino Acids (250ml)', packaging: 'Shampoo bottle', sort_order: 106 },
  { brand: 'Der Duft', name: 'Scalp Clear Anti-Dandruff Shampoo', category: 'Hair Care', description: 'Neem, Tea Tree Oil & Salicylic Acid (250ml)', packaging: 'Shampoo bottle', sort_order: 107 },
  { brand: 'Der Duft', name: 'Reviver Hair Repair Shampoo', category: 'Hair Care', description: 'With Vitamin E - Nourishes & Fortifies (300ml)', packaging: 'Shampoo bottle', sort_order: 108 },
  { brand: 'Pure Roots', name: 'Hair Removal Cream (Gold / Papaya / Rose / Aloe)', category: 'Hair Care', description: 'Anti-Darkening Hair Removal for Normal Skin', packaging: 'Squeeze tube + scraper', sort_order: 109 },
  { brand: 'Astaberry Ikin', name: 'Diamond Hair Remover Creme', category: 'Hair Care', description: 'Hair Removal Cream for Dry Skin (60g)', packaging: 'Squeeze tube', sort_order: 110 },
  { brand: 'Astaberry Ikin', name: 'Skin Brightening Hair Remover Creme', category: 'Hair Care', description: 'Strawberry & Aloe Vera Extract (60g)', packaging: 'Squeeze tube', sort_order: 111 },
  { brand: 'Astaberry Ikin', name: 'Rose Hair Remover Creme', category: 'Hair Care', description: 'Carrot & Soy Protein Extract (60g)', packaging: 'Squeeze tube', sort_order: 112 },
  { brand: 'Rivaz', name: 'Natural Mehandi Cone', category: 'Accessories', description: '100% Natural Henna Cones', packaging: 'Decorated green box pack', sort_order: 113 },
  { brand: 'Tinkle', name: 'Eyebrow Razor Set', category: 'Accessories', description: 'Stainless Steel Safety Cover (3 Pcs/Set)', packaging: 'Blister card pack', sort_order: 114 },
  { brand: 'Max', name: 'Shave Body Ergonomic Razor', category: 'Accessories', description: 'Nick-Free Stainless Steel Blade (6 Pieces)', packaging: 'Blister card pack', sort_order: 115 },
  { brand: 'Max', name: 'Soft Care Disposable Razors', category: 'Accessories', description: 'Practitioners of Shaving Technology (12 Pcs)', packaging: 'Razor box pack', sort_order: 116 },
  { brand: 'Celona', name: 'Vitamin E Nail Enamel', category: 'Accessories', description: 'Green Apple, Rose, Cherry, Lemon Shades', packaging: 'Nail polish bottles', sort_order: 117 },
  { brand: 'MAC', name: 'True Crush / Disco Matt / Shine Pop', category: 'Accessories', description: 'Instant Dry Nail Polish Set', packaging: 'Wholesale display pack', sort_order: 118 },
  { brand: 'Ocean Beauty', name: 'Fashion Nail / Party Legend', category: 'Accessories', description: 'Press-on Nail Art Set (12 Pcs)', packaging: 'Display card pack', sort_order: 119 },
  { brand: 'Keli', name: 'Makeup Powder Puff Set', category: 'Accessories', description: 'High Quality Antibacterial Puffs', packaging: 'Puff storage containers', sort_order: 120 },
  { brand: 'Minisigreen', name: 'Dhoop Se Dosti', category: 'Accessories', description: 'Fragrant Dhoop Incense Pack', packaging: 'Retail pack', sort_order: 121 },
  { brand: 'Jiandan', name: 'Cute Erasable Gel Pen (JD-5909C)', category: 'Accessories', description: 'Cute Character Erasable Gel Pens', packaging: 'Stationery box', sort_order: 122 },
  { brand: 'Mr. Animal', name: '2B Hexagonal Pencils & Stickers', category: 'Accessories', description: 'Lead-Free Smooth Writing Pencils (12 Pcs)', packaging: 'Pencil box', sort_order: 123 },
  { brand: 'Marvel / Avengers', name: 'Spider-Man 2B Pencil Set', category: 'Accessories', description: 'Character Stationery Pencils', packaging: 'Pencil pack', sort_order: 124 },
  { brand: 'Classroom', name: 'Favorite Food Modeling Clay (HMA-292)', category: 'Accessories', description: 'Non-Toxic Clay Set', packaging: 'Clay set box', sort_order: 125 },
]

export const DEFAULT_BRANDING = {
  business_name: 'Divine Traders',
  emblem: 'DT',
  tagline: 'We Deals in Wholesale — Cosmetics, FMCG & General Products',
  sub_tagline: 'Your Trust, Our Quality',
  phone1: '+91 7529078910',
  phone2: null,
  address: 'SCO No. 85, 1st Floor, Panchkula Shopping Complex, Peer Muchalla',
  admin_password: 'admin@divine',
}
